version: "3.3"

services:
  library-db:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  backend:
    image: sdt-backend
#    ports:
#      - "8080:8080"
#    depends_on:
#      - library-db

  frontend:
    image: sdt-frontend
    ports:
      - "80:80"
#    links:
#      - backend

volumes:
  data:
  logs: